### ISSUE TITLE
Investigate cluster autoscaling

### ISSUE THREAD

**Issue by vparekh94** [astronomer/terraform-aws-astronomer-enterprise#10]
We've had 2 customers report that their EKS clusters are not autoscaling past the `NodeDesiredSize`.

Did some investigation with @andrewhharmon and it looks like you may have to add an extra policy to get the cluster autoscaler to work on EKS.

https://eksworkshop.com/scaling/deploy_ca/

https://caylent.com/kubernetes-autoscaling/

We should add this to our tf, as well as our guides that show how to deploy the cluster.

**Comment by vparekh94** [comment]
Thanks for looking into this @sjmiller609

**Comment by sjmiller609** [comment]
I have reproduced the issue, confirming that it's an issue with the default configuration applied in this automation.

**Comment by sjmiller609** [comment]
canonical location of cluster autoscaling https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

**Comment by sjmiller609** [comment]
the cluster auto scaler runs as a deployment in k8s. some people recommend attaching the required IAM policy as an instance profile to the worker nodes, but I find this undesirable because all airflow tasks would then get that authorization. k8s docs say to use a node group for this reason (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md), but I find it a costly proposition to run an autoscaling group only for the purpose of running the cluster autoscaler.

**Comment by sjmiller609** [comment]
In my past experience with ECS, we found an effective solution by using AWS lambda in combination with ASG lifecycle hooks and cloud watch events. On first glance, the k8s cluster autoscaler looks like it uses similar logic. I will dig in a bit and see how it works, maybe they support deploying to a lambda or something. that would be convenient because the IAM permissions can be cleanly separated. If not, I will run it as a deployment, but I will use a different method than instance profiles to grant the permissions to the pods of the deployment (perhaps k8s secrets)

**Comment by sjmiller609** [comment]
"Cluster autoscaler does not support Auto Scaling Groups which span multiple Availability Zones; instead you should use an Auto Scaling Group for each Availability Zone and enable the --balance-similar-node-groups feature. If you do use a single Auto Scaling Group that spans multiple Availability Zones you will find that AWS unexpectedly terminates nodes without them being drained because of the rebalancing feature." we do indeed use a single ASG. In the case of ECS, we made use of the EC2 'terminating:wait' lifecycle hook to prevent this exact issue (as outlined in this AWS blog post https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/)

**Comment by sjmiller609** [comment]
"EBS volumes cannot span multiple AWS Availability Zones ... If AWS Auto Scaling Group ... moves [a] Pod into [a node in a different AZ], the Persistent volume in previous AZ will not be available from the new AZ. The Workaround is using a single AZ for the k8s/EKS nodes."

**Comment by sjmiller609** [comment]
i'm investigating more on this EKS, ASG, AZ, and autoscaling situation. the quickstart AWS EKS stuff does indicate 1 ASG for multiple AZs, which Google claims does not work. https://github.com/aws-quickstart/quickstart-amazon-eks This repo includes a deployment of the autoscaler with this configuration https://github.com/aws-quickstart/quickstart-amazon-eks/blob/master/templates/amazon-eks-cluster-autoscaler.template.yaml , which seems to contradict google's claim.

**Comment by sjmiller609** [comment]
My plan going forward is to first simply attach the required policy to all nodes via an instance profile, then investigate the 'gotcha' around multi-AZ ASGs. After I come to understand that, I can work to secure the policy. I am coming around on the node group - perhaps just 2 instances of a very small instance type would be tolerable cost for running the cluster autoscaler.

**Comment by sjmiller609** [comment]
Add helm deployment in system-components https://github.com/astronomer/terraform-kubernetes-astronomer-system-components/commit/8c99964687cfed027a32ac5bb370b76f07c37074

**Comment by sjmiller609** [comment]
Enable in the terraform-aws-astronomer-aws module https://github.com/astronomer/terraform-aws-astronomer-aws/pull/24/files

**Comment by sjmiller609** [comment]
I am opening a new issue to handle least-privilege https://github.com/astronomer/terraform-aws-astronomer-enterprise/issues/12, which is required before this automation is used for a multi-tenant scenario. This PR closes this issue: https://github.com/astronomer/terraform-aws-astronomer-enterprise/pull/11

**Comment by sjmiller609** [comment]
re-opening to fix the project automation
